* 基线分析语法文件.
CD '/Users/leyixu/Ai cowork/research'.
PRESERVE.
SET UNICODE ON.
GET DATA /TYPE=TXT
  /FILE='stroke_baseline.csv'
  /ENCODING='UTF8'
  /DELCASE=LINE
  /DELIMITERS=","
  /ARRANGEMENT=DELIMITED
  /FIRSTCASE=2
  /DATATYPEMIN PERCENTAGE=95.0
  /VARIABLES=
  分组 A2
  组别说明 A20
  患者ID A10
  卒中亚型 A4
  时间点 A2
  FMA_LE F3.0
  ADL F3.0
  BBS F3.0
  TUGT A5
  MAS A2
  CSS F3.0.
RESTORE.

VARIABLE LEVEL 分组 卒中亚型 MAS TUGT (NOMINAL).
VARIABLE LEVEL FMA_LE ADL BBS CSS (SCALE).
VALUE LABELS 分组
  'G1' '双侧真实'
  'G2' '单侧真实+对侧安慰剂'
  'G3' '单侧真实'
  'G4' '空白对照(CT)'.

* 描述性统计.
DESCRIPTIVES VARIABLES=FMA_LE ADL BBS CSS
  /STATISTICS=MEAN STDDEV MIN MAX.

* 按分组描述性统计.
MEANS TABLES=FMA_LE ADL BBS CSS BY 分组
  /CELLS=MEAN COUNT STDDEV MIN MAX.

* 正态性检验 (Shapiro-Wilk) 和 方差齐性检验 (Levene).
EXAMINE VARIABLES=FMA_LE ADL BBS CSS BY 分组
  /PLOT NONE
  /STATISTICS DESCRIPTIVES
  /CINTERVAL 95
  /MISSING LISTWISE
  /NOTOTAL.

* 单因素方差分析 (用于正态且方差齐的变量).
ONEWAY FMA_LE ADL BBS CSS BY 分组
  /STATISTICS DESCRIPTIVES HOMOGENEITY
  /MISSING ANALYSIS
  /POSTHOC=TUKEY ALPHA(0.05).

* 非参数检验 (Kruskal-Wallis H 检验).
NPAR TESTS
  /K-W=FMA_LE ADL BBS CSS BY 分组(1 4)
  /MISSING ANALYSIS.

* 卡方检验（卒中亚型分布）.
CROSSTABS
  /TABLES=分组 BY 卒中亚型
  /FORMAT=AVALUE TABLES
  /STATISTICS=CHISQ
  /CELLS=COUNT ROW
  /COUNT ROUND CELL.

* 输出到查看器文件.
OUTPUT SAVE OUTFILE='baseline_results.spv'.
